name: Release snapshot
on:
  push:
    branches:
      - master
      - snapshot
jobs:
  build:
    build-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run Maven
        run: mvn --batch-mode --update-snapshots verify deploy
